### ISSUE TITLE
Doesn't work with Browserify

### ISSUE THREAD

**Issue by kvnneff** [dekujs/assert-element#3]
Node's assert module is bundled when using Browserify and it acts differently than component's assert when checking if two arrays are equal.

`component/assert` returns true when `assert.strictEqual(['a', 'b'], ['a', 'b'])` whereas with node's assert module: `AssertionError: ["a","b"] === ["a","b"]`.

**Comment by dominicbarnes** [comment]
Are you sure? I've used both extensively and `strictEqual` functions identically.

Just to be sure, I looked at [component/assert's code](https://github.com/component/assert/blob/0.5.1/index.js#L89), and sure enough it's using `===` as expected.

**Comment by kvnneff** [comment]
hmm I'm pretty sure but I'll check again tomorrow and update this issue.

**Comment by kvnneff** [comment]
Try this with node, it should throw an error:

```
var assert = require('assert')
var arrayOne = ['a', 'b']
var arrayTwo = ['a', 'b']

assert.strictEqual(arrayOne, arrayTwo)
```

[component/assert](https://github.com/component/assert) returns true because it uses [jkroso/equals](https://github.com/jkroso/equals) which will iterate through an array and compare each value in the array.

With Node's assert module I've always had to do it myself.  This will not throw an error:

```
var assert = require('assert')
var arrayOne = ['a', 'b']
var arrayTwo = ['a', 'b']
var i = arrayOne.length

while (i--) {
 assert.strictEqual(arrayOne[i], arrayTwo[i])
}
```

**Comment by kvnneff** [comment]
Oh I just now clicked the link to `component/assert` and I see what you're saying.  I must have been looking at the code for deepEquals originally.  I had a specific issue with `assert-element` let me see if I can recreate it.

**Comment by dominicbarnes** [comment]
Ok, I wouldn't be surprised if there were some caveats between these different libraries, but I'm hoping they're edge-cases more than anything. If you can find the exact failure scenario, or at least something reproducible, we can re-open this.
